### ISSUE TITLE
what's wrong with this

### ISSUE THREAD

**Issue by embees28** [dante4rt/sonic-odyssey-bot#3]
SyntaxError: Unexpected token '='
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/root/sonic-odyssey-bot/src/solanaUtils.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by dante4rt** [comment]
> SyntaxError: Unexpected token '=' at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:85:18) at Object. (/root/sonic-odyssey-bot/src/solanaUtils.js:9:5) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

Could you give me clear steps to reproduce these issues? Thanks.

**Comment by embees28** [comment]
I encountered this problem when doing npm start

**Comment by ndaru742** [comment]
Sending SOL from account 1: 2VwMqzWKniJFjNSjKcpPVzdfcNE24R6eHjeGHXxykDLP
Failed to send SOL to D8U2JGgm5SnP1mQHzah691x1KRJMimZpyHf2tC8v8YLi: SendTransactionError: Simulation failed. 
Message: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.. 
Logs: 
[]. 
Catch the `SendTransactionError` and call `getLogs()` on it for full details.
    at Connection.sendEncodedTransaction (/workspace/sonic/sonic-odyssey-bot/node_modules/@solana/web3.js/lib/index.cjs.js:8114:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (/workspace/sonic/sonic-odyssey-bot/node_modules/@solana/web3.js/lib/index.cjs.js:8079:20)
    at async Connection.sendTransaction (/workspace/sonic/sonic-odyssey-bot/node_modules/@solana/web3.js/lib/index.cjs.js:8070:12)
    at async sendAndConfirmTransaction (/workspace/sonic/sonic-odyssey-bot/node_modules/@solana/web3.js/lib/index.cjs.js:2273:21)
    at async sendSol (/workspace/sonic/sonic-odyssey-bot/src/solanaUtils.js:27:21)
    at async /workspace/sonic/sonic-odyssey-bot/index.js:131:9 {
  signature: '',
  transactionMessage: 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.',
  transactionLogs: []
}

**Comment by dante4rt** [comment]
> I encountered this problem when doing npm start

Show me your NodeJS version.

**Comment by dante4rt** [comment]
> Attempt to debit an account but found no record of a prior credit

Did you have a balance?
