### ISSUE TITLE
Error Output

### ISSUE THREAD

**Issue by adryan089** [dante4rt/sonic-odyssey-bot#4]
I encountered an error that displays the following code:

Sending SOL from account 1: 6rNqnAQ84AUfyr38xwR9F9ZCnENrq4X5BiMSb8qk8LxB
Failed to send SOL to A5aC9bzpTXfQWuAEbdRcXfr2ktRZ5QPTtsibzQia7XVt: SendTransactionError: Simulation failed.
Message: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit..
Logs:
[].
Catch the `SendTransactionError` and call `getLogs()` on it for full details.
    at Connection.sendEncodedTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules\@solana\web3.js\lib\index.cjs.js:8134:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Connection.sendRawTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules\@solana\web3.js\lib\index.cjs.js:8099:20)
    at async Connection.sendTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules\@solana\web3.js\lib\index.cjs.js:8090:12)
    at async sendAndConfirmTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules\@solana\web3.js\lib\index.cjs.js:2273:21)
    at async sendSol (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\src\solanaUtils.js:27:21)
    at async F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\index.js:131:9 {
  signature: '',
  transactionMessage: 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.',
  transactionLogs: []

balance on 2 SOL accounts and that's from Sonic's own faucet... but this bot still has an error. is there any solution?

**Comment by dante4rt** [comment]
> I encountered an error that displays the following code:
> 
> Sending SOL from account 1: 6rNqnAQ84AUfyr38xwR9F9ZCnENrq4X5BiMSb8qk8LxB Failed to send SOL to A5aC9bzpTXfQWuAEbdRcXfr2ktRZ5QPTtsibzQia7XVt: SendTransactionError: Simulation failed. Message: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.. Logs: []. Catch the `SendTransactionError` and call `getLogs()` on it for full details. at Connection.sendEncodedTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules@solana\web3.js\lib\index.cjs.js:8134:13) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Connection.sendRawTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules@solana\web3.js\lib\index.cjs.js:8099:20) at async Connection.sendTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules@solana\web3.js\lib\index.cjs.js:8090:12) at async sendAndConfirmTransaction (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\node_modules@solana\web3.js\lib\index.cjs.js:2273:21) at async sendSol (F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\src\solanaUtils.js:27:21) at async F:\CryptoCurrency Data\Bot\Testnet\SONIC\2\index.js:131:9 { signature: '', transactionMessage: 'Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.', transactionLogs: []
> 
> balance on 2 SOL accounts and that's from Sonic's own faucet... but this bot still has an error. is there any solution?

I think it's an RPC problem, not an issue with the code. Since it's accessed by tons of transactions and is still on devnet, I think it can't handle the load yet. Just try again, and use another wallet if possible, since I and most of my subscribers are mostly fine.
